config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'welcome/index'
  
  resources :albums do
  	resources :photos do
  		member do
	      post 'add_cover_photo'
	    end
  	end
  end

  resources :comments do 
    collection do
     get 'commentable_area'
    end  
  end  
  root 'albums#index'
end

app/models/album.rb
class Album < ApplicationRecord
	has_many  :photos, dependent: :destroy
	has_many :comments, :as => :commentable

	belongs_to :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
	has_many :comments, dependent: :destroy
	validates :title, presence: true,
                    length: { minimum: 5 }
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :commentable, :polymorphic => true
end

app/models/photo.rb
class Photo < ApplicationRecord
	belongs_to :album
	mount_uploader :image, ImageUploader
	has_many :comments, :as => :commentable
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
   has_many :albums
   has_many :photos, through: :albums
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController

  def show
    @album = Album.find(params[:id])
    @photos = @album.photos
  end

	def new
		@album = current_user.albums.new
  end

  def create
  	
    @album = current_user.albums.new(album_params)
    if @album.save
      redirect_to @album
    else
      render 'new'
    end
  end

  def index
    @albums = current_user.albums
  end

  def edit
    @album = Album.find(params[:id])
  end

  def update
    @album = Album.find(params[:id])
  
    if @album.update(album_params)
      redirect_to album_path
    else
      render 'edit'
    end
  end

  def destroy
    @album = Album.find(params[:id])
    if @album.destroy
      redirect_to @album
    end
  end
  
  def commentable_area
  end  

  private
    def album_params
      params.require(:album).permit(:name, :description)
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email, :password])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :email, :password, :current_password, :is_female, :date_of_birth])
  end

  def after_sign_in_path_for(resource)
    root_path
  end
  def after_sign_up_path_for(resource)
    root_path
  end  
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
 
  #http_basic_authenticate_with name: "dhh", password: "secret", except: [:update, :destroy]

  def show
    @article = Article.find(params[:id])
  end

  def index
    @articles = Article.all
  end	

  def new
  	@article = Article.new
  end

  def edit
    @article = Article.find(params[:id])
  end

  def create
  	#render plain: params[:article].inspect
    #@article = Article.new(params[:article])
    #@article = Article.new(params.require(:article).permit(:title, :text))
    @article = Article.new(article_params)
    #@article.save
    #redirect_to @article
    if @article.save
      redirect_to @article
    else
      render 'new'
    end
  end

  def update
    @article = Article.find(params[:id])
 
    if @article.update(article_params)
      redirect_to @article
    else
      render 'edit'
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy
 
    redirect_to articles_path
  end

  private
    def article_params
      params.require(:article).permit(:title, :text)
    end
   
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def commentable_area
    if params[:album_id].present?
      @album = current_user.albums.find(params[:album_id])
      @comment = @album.comments.new
    elsif params[:photo_id].present?
      @photo = current_user.photos.find(params[:photo_id])
      @comment = @photo.comments.new
    end
    
  end 

  def create
    if params[:comment][:album_id].present?
      @album = current_user.albums.find(params[:comment][:album_id])
      @comment = @album.comments.new(comment_params)
      if @comment.save
        flash[:notice] = "Successfully created comment."
        redirect_to root_path
      else
        render  'new'
      end
    elsif params[:comment][:photo_id].present?
      @photo = current_user.photos.find(params[:comment][:photo_id])
      @comment = @photo.comments.new(comment_params)
      if @comment.save
        flash[:notice] = "Successfully created comment."
        redirect_to root_path
      else
        render  'new'
      end
    end
  end

  private
    def comment_params
      params.require(:comment).permit(:content)
    end  
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  
  before_action :set_event, only: [:new,:create,:show, :destroy]

	def new
		@photo = @album.photos.new
  end

  def create
		@photo = @album.photos.new(photo_params)
    if @photo.save
      redirect_to @album
    else
      render 'show'
    end
  end

  def show
    @photo = Photo.find(params[:id])
  end

  def destroy
    @photo = Photo.find(params[:id])
    if @photo.destroy
     redirect_to album_path(@album)
    else
      render 'album/show'
    end
  end

  def add_cover_photo
    @album = current_user.albums.find(params[:album_id])
    @photo = @album.photos.find(params[:id])
    @album.update_column('cover_id', @photo.id)
    redirect_to @album
  end

  private

    def set_event
      @album = current_user.albums.find(params[:album_id])
    end

    def photo_params
      params.require(:photo).permit(:name, :image)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/album_helper.rb
module AlbumHelper
	#Album.find(1).comments
	def get_image(cover_id)
		@photo = Photo.find_by_id(cover_id)
		@photo.present? ? @photo.image : "download.jpg"
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/albums/edit.html.erb
<div class="container">
	<div class=".col-md-6 col-md-offset-5">
	  <h1>Edit article</h1>
	  <%= form_for @album do |form| %>
        <p>
          <%= form.label :name %><br>
          <%= form.text_field :name %>
        </p>
 
        <p>
          <%= form.label :description %><br>
          <%= form.text_area :description %>
        </p>
 
        <p>
           <%= form.submit %>
        </p>
        <%= link_to "New Album", new_album_path %>
    <% end %>
	</div>
</div>

app/views/albums/index.html.erb
<div class="container">
    <h3><%= link_to "New Album", new_album_path %></h3>
      <% @albums.each do |album|%>
      <div class="col-md-6">
        <p>
          <strong>Name:</strong>
          <%= album.name %>
        </p>
        <p>
          <strong>Description:</strong>
          <%= album.description %>
        </p>
        <p><%= link_to album_path(album) do %>
                      <%= image_tag(get_image(album.cover_id), :size => "260x180") %>
            <% end %> | <%= link_to "Edit", edit_album_path(album)%>| <%= link_to "Delete", album_path(album),
              method: :delete,
              data: { confirm: 'Are you sure?' }%></p>
        <p></p>
        <input type="button" value="show comments" onclick="msg(<%= album.id %>)">
        <div class="hidetext" id="album_<%= album.id %>">
          <p>
            <% album.comments.each do |comment| %>
              <strong>Comment:</strong>
              <%= comment.content %><br>
            <% end %>
          </p> 
        </div>      
        <p>
          <%= link_to "Add comments on Album", commentable_area_comments_path(album_id: album.id), remote: true %>
          <div id="album_comment_<%= album.id %>"></div>
        </p>
      </div>
      <% end %>
</div>
<script type="text/javascript">

  $("#album_comment_").click(function(){
    $("div").show();
  });
  $(".hidetext").hide();
  function msg(id) {
      $('#album_'+id).toggle();
  }

</script>

app/views/albums/new.html.erb
<div class="container">
	<div class=".col-md-6 col-md-offset-5">
		<h1>New Alnum</h1>
		<%= form_for @album do |form| %>
      <p>
        <%= form.label :name %><br>
        <%= form.text_field :name %>
      </p>
 
      <p>
        <%= form.label :description %><br>
        <%= form.text_area :description %>
      </p>
      
      <p>
         <%= form.submit %>
      </p>
    <% end %>
	</div>
</div>

app/views/albums/show.html.erb
<div class="container">
    <h3><%= link_to "Add Photos in Album", new_album_photo_path(@album.id)%></h3>
    <% @photos.each do |photo|%>
    <div class="col-md-6">
      <h4><%= photo.name %> |
      <%= link_to "Delete Photo" ,album_photo_path(@album.id, photo),
              method: :delete,
              data: { confirm: 'Are you sure?' }%> | <%= link_to "Add cover photo", add_cover_photo_album_photo_path(@album, photo), method: :post %> </h4>
      <%= image_tag("#{photo.image}" , :size => "260x180")%>     
      <p>
        <%= link_to "Add comments on Photo",  commentable_area_comments_path(photo_id:photo), remote: true %>
        <div id="photo_comment_<%= photo.id %>"></div>
      </p>
       <input type="button" value="show comments" onclick="msg(<%= photo.id %>)"> 
       <div class="hidetext" id="album_<%= photo.id %>">
        <p>
          <% photo.comments.each do |comment| %>
            <strong>Comment:</strong>
            <%= comment.content %><br>
          <% end %>
        </p> 
      </div>   
      </div>        
    <% end %>
</div>
<script type="text/javascript">
  $("#photo_comment_").click(function(){
    $("div").show();
  });
  $(".hidetext").hide();
  function msg(id) {
      
          $('#album_'+id).toggle();
  }
</script>

app/views/articles/_form.html.erb
<%= form_with model: @article , local: true do |form| %>
 
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@article.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>
 
  <p>
    <%= form.label :text %><br>
    <%= form.text_area :text %>
  </p>
 
  <p>
    <%= form.submit %>
  </p>
 
<% end %>

app/views/articles/edit.html.erb
<div class="container">
<div class=".col-md-6 col-md-offset-5">
<h1>Edit article</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', articles_path %>
</div></div>

app/views/articles/index.html.erb
<div class="container">
<div class=".col-md-6 col-md-offset-5">
<h1>Listing articles</h1>
<%= link_to 'New article', new_article_path %> 
<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
    <th colspan="3"></th>
  </tr>
 
  <% @articles.each do |article| %>
    <tr>
      <td><%= article.title %></td>
      <td><%= article.text %></td>
      <td><%= link_to 'Show', article_path(article) %></td>
      <td><%= link_to 'Edit', edit_article_path(article) %></td>
       <td><%= link_to 'Destroy', article_path(article),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>
</div></div>

app/views/articles/new.html.erb
<div class="container">
<div class=".col-md-6 col-md-offset-5"><h1>New article</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', articles_path %>
</div></div>

app/views/articles/show.html.erb
<div class="container">
<div class=".col-md-6 col-md-offset-5">
<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>
 
<p>
  <strong>Text:</strong>
  <%= @article.text %>
</p>

<h2>Comments</h2>
<%= render @article.comments %>

<h2>Add a comment:</h2>
<%= render 'comments/form' %>
 
<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>
</div></div>

app/views/comments/_form.html.erb
<h2>New Comment</h2>
<%= form_for @comment, remote: true do |f| %>
  <p>
    <%= f.label :content %><br />
    <%= f.text_area :content %>
    <%= f.hidden_field :album_id, value: @album.try(:id)%>
    <%= f.hidden_field :photo_id, value: @photo.try(:id)%>
  </p>
  <p><%= f.submit "Submit" %></p>
<% end %>

app/views/comments/commentable_area.js.erb
<% if (params[:album_id]).present? %> 
  $('#album_comment_<%= @album.id %>').html("");
  $('#album_comment_<%= @album.id %>').html('<%= escape_javascript( render :partial => "form") %>');
 
<% elsif (params[:photo_id]).present? %>
  $('#photo_comment_<%= @photo.id %>').html("");
  $('#photo_comment_<%= @photo.id %>').html('<%= escape_javascript( render :partial => "form") %>');
<% end %>

app/views/layouts/_header.html.erb
<header class="navbar navbar-inverse">
  <div class="container">
    <%= link_to "demo app", '#', id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
      <% if current_user %>
      	<li><%= link_to "Albums", albums_path %></li>
        <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
        <li><%= link_to 'Edit registration' , edit_user_registration_path%></li>
      <% else %>
        <li><%= link_to "Sign in",new_user_session_path %></li>
        <li><%= link_to "Sign Up",new_user_registration_path %></li>
      <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Demo</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= yield %>
  </body>
</html>

app/views/photos/new.html.erb
<div class="container">
	<div class=".col-md-6 col-md-offset-5">
		<h1>Add New Photo</h1>
		<%= form_for @photo, url: album_photos_path(@album.id) do |f| %>
      <p>
        <%= f.label :name %><br />
        <%= f.text_field :name %>
      </p>
      <p>
        <%= f.file_field :image %>
      </p>
      <p><%= f.submit %></p> 
    <% end %>
	</div>
</div>

app/views/photos/show.html.erb
<div class="container">
	<div class=".col-md-6 col-md-offset-5">
		<h1>Show New Photo</h1>
		<h3>
          <%= @photo.name %>
        </h3>
        <%= image_tag("#{@photo.image}" , :size => "360x280")%>
	</div>
</div>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/welcome/index.html.erb
<h1>Hello, Rails!</h1>
<%= link_to 'My Blog', controller: 'articles' %>